### ISSUE TITLE
请问测试多个数据集时，如何在optional arguments中添加参数？

### ISSUE THREAD

**Issue by PangJian123** [open-mmlab/OpenUnReID#16]
你好，我尝试在optional arguments中添加测试集的参数，但是会报错。命令如下：GPUS=1 bash dist_train.sh source_pretrain /home/pj/OpenUnReID-master/tools/source_pretrain/logs/ TRAIN.LOADER.samples_per_gpu 64 TEST.datasets ['dukemtmc', 'market1501',]。请问是不是我的参数格式有问题？

**Comment by yxgeee** [comment]
你好，可以把报错截图我看一下吗

**Comment by PangJian123** [comment]
(reid) pj@pj-PC:~/OpenUnReID-master/tools$ GPUS=1 bash dist_train.sh source_pretrain /home/pj/OpenUnReID-master/tools/source_pretrain/logs/ TRAIN.LOADER.samples_per_gpu 64 TEST.datasets ['dukemtmc', 'market1501',]
+ PYTHON=python
+ METHOD=source_pretrain
+ WORK_DIR=/home/pj/OpenUnReID-master/tools/source_pretrain/logs/
+ PY_ARGS='TRAIN.LOADER.samples_per_gpu 64 TEST.datasets [dukemtmc, market1501,]'
+ GPUS=1
+ true
+ PORT=22711
++ nc -z 127.0.0.1 22711
++ echo 127
+ status=127
+ '[' 127 '!=' 0 ']'
+ break
+ python -m torch.distributed.launch --nproc_per_node=1 --master_port=22711 --use_env source_pretrain/main.py source_pretrain/config.yaml --work-dir=/home/pj/OpenUnReID-master/tools/source_pretrain/logs/ --launcher=pytorch --tcp-port=22711 --set TRAIN.LOADER.samples_per_gpu 64 TEST.datasets '[dukemtmc,' 'market1501,]'
Traceback (most recent call last):
  File "source_pretrain/main.py", line 142, in <module>
    main()
  File "source_pretrain/main.py", line 72, in main
    args, cfg = parge_config()
  File "source_pretrain/main.py", line 61, in parge_config
    cfg_from_list(args.set_cfgs, cfg)
  File "/home/pj/OpenUnReID-master/openunreid/utils/config.py", line 22, in cfg_from_list
    assert len(cfg_list) % 2 == 0
AssertionError
Traceback (most recent call last):
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/pj/anaconda3/envs/reid/bin/python', '-u', 'source_pretrain/main.py', 'source_pretrain/config.yaml', '--work-dir=/home/pj/OpenUnReID-master/tools/source_pretrain/logs/', '--launcher=pytorch', '--tcp-port=22711', '--set', 'TRAIN.LOADER.samples_per_gpu', '64', 'TEST.datasets', '[dukemtmc,', 'market1501,]']' returned non-zero exit status 1.


这个错误感觉是命令行中不支持输入列表参数这种形式。

**Comment by yxgeee** [comment]
试一下`TEST.datasets dukemtmcreid,market1501`

**Comment by PangJian123** [comment]
解决了，谢谢！
