### ISSUE TITLE
why source_pretrain wrong?

### ISSUE THREAD

**Issue by 969191832** [open-mmlab/OpenUnReID#21]
Traceback (most recent call last):
  File "source_pretrain/main.py", line 142, in <module>
    main()
  File "source_pretrain/main.py", line 124, in main
    runner.run()
  File "/workspace/mnt/storage/zsl/debug_observe/OpenUnReID/openunreid/apis/runner.py", line 122, in run
    self.train()
  File "/workspace/mnt/storage/zsl/debug_observe/OpenUnReID/openunreid/apis/runner.py", line 212, in train
    self.train_loader.new_epoch(self._epoch)
  File "/workspace/mnt/storage/zsl/debug_observe/OpenUnReID/openunreid/data/utils/dataset_wrapper.py", line 89, in new_epoch
    self.iter = iter(self.loader)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 719, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'SubPolicy.__init__.<locals>.<lambda>'
Traceback (most recent call last):
  File "source_pretrain/main.py", line 142, in <module>
    main()
  File "source_pretrain/main.py", line 124, in main
    runner.run()
  File "/workspace/mnt/storage/zsl/debug_observe/OpenUnReID/openunreid/apis/runner.py", line 122, in run
    self.train()
  File "/workspace/mnt/storage/zsl/debug_observe/OpenUnReID/openunreid/apis/runner.py", line 212, in train
    self.train_loader.new_epoch(self._epoch)
  File "/workspace/mnt/storage/zsl/debug_observe/OpenUnReID/openunreid/data/utils/dataset_wrapper.py", line 89, in new_epoch
    self.iter = iter(self.loader)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 719, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'SubPolicy.__init__.<locals>.<lambda>'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)

**Comment by yxgeee** [comment]
Please see **(f)** in https://github.com/open-mmlab/OpenUnReID/blob/master/docs/INSTALL.md#install-openunreid

**Comment by 969191832** [comment]
thanks
